export const CHANGE_SEARCH_TEXT = "CHANGE_SEARCH_TEXT";
export const UPLOAD_DATA = "UPLOAD_DATA";
export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const SET_SORT_RULE = "SET_SORT_RULE";

export const SET_FILTER_INPUT = "SET_FILTER_INPUT";
export const ADD_DROPDOWN_CHECKED = "ADD_DROPDOWN_CHECKED";
export const REMOVE_DROPDOWN_CHECKED = "REMOVE_DROPDOWN_CHECKED";
export const SET_SHOW_FILTERS = "SET_SHOW_FILTERS";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const APPLY_FILTERS = "APPLY_FILTERS";

export const SET_CUR_PAGE = "SET_CUR_PAGE";
export const SET_PAGE_COUNT = "SET_PAGE_COUNT";

export const SET_CHECK_COUNT = "SET_CHECK_COUNT";
export const ADD_CHECKED = "ADD_CHECKED";
export const REMOVE_CHECKED = "REMOVE_CHECKED";
export const CHECK_ALL = "CHECK_ALL";
export const UNCHECK_ALL = "UNCHECK_ALL";
export const SET_CURRENT_FILTER_IDS = "SET_CURRENT_FILTER_IDS";

export const SET_ITEMFORM_INPUT = "SET_ITEMFORM_INPUT";
export const SHOW_ITEM_FORM = "SHOW_ITEM_FORM";
export const HIDE_ITEM_FORM = "HIDE_ITEM_FORM";
export const SET_ITEMFORM_ALL_INPUTS = "SET_ITEMFORM_ALL_INPUTS";
