export const CHANGE_SEARCH_TEXT = "CHANGE_SEARCH_TEXT";
export const UPLOAD_DATA = "UPLOAD_DATA";
export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const SET_SORT_RULE = "SET_SORT_RULE";

export const SET_CUR_PAGE = "SET_CUR_PAGE";
export const SET_PAGE_COUNT = "SET_PAGE_COUNT";
